name: Build and deploy test site to Netlify

on:
  push:
    branches: [ "dev/**" ]
    paths:
      - .github/workflows/test-deploy.yaml
      - src/components/**
      - src/model/**
      - src/pages/**
      - src/slice/**
      - src/theme/**
      - src/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "npm"
    - name: Install dependencies
      run: npm ci
    - name: Set up environment variables
      run: | 
        echo "VITE_APP_TITLE=snack" > .env
        echo "VITE_SERVER_ADDRESS=$SERVER_ADDRESS" >> .env
        echo "VITE_COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID" >> .env
        echo "VITE_COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID" >> .env
        echo "VITE_FIREBASE_APIKEY=$FIREBASE_APIKEY" >> .env
        echo "VITE_FIREBASE_APP_ID=$FIREBASE_APP_ID" >> .env
        echo "VITE_FIREBASE_MSG_SENDER_ID=$FIREBASE_MSG_SENDER_ID" >> .env
        echo "VITE_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
        echo "VITE_FIREBASE_VAPID_KEY=$FIREBASE_VAPID_KEY" >> .env
      env:
        COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_DEV_USER_POOL_ID }}
        COGNITO_CLIENT_ID: ${{ secrets.COGNITO_DEV_CLIENT_ID }}
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        FIREBASE_APIKEY: ${{ secrets.FIREBASE_APIKEY }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MSG_SENDER_ID: ${{ secrets.FIREBASE_MSG_SENDER_ID }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_VAPID_KEY: ${{ secrets.FIREBASE_VAPID_KEY }}
    - name: Build
      run: npm run build
    - name: Upload the artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-dist
        path: dist
    - name: Deploy the test site to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}